version: "3.3"

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./src/:/app/src/
    networks:
      - global

networks:
  global: